# Numpy Array

In [1]:
import numpy as np
np.array([1, 2, 3],ndmin=4)

array([[[[1, 2, 3]]]])

In [2]:
type([1, 2, 3])

list

In [3]:
#Upcasting:

In [4]:
np.array(['1', 2,9.0])

array(['1', '2', '9.0'], dtype='<U3')

In [5]:
#two dimensions

In [6]:
a = np.array([[1, 2], [3, 4], [4,5]])
a.dtype

dtype('int32')

In [7]:
#Minimum dimensions 2:

In [8]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
#dtype

In [10]:
 np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [11]:
#Data-type consisting of more than one element:

In [12]:
x = np.array([(1,2),(3,4)],dtype=[('a','<f8'),('b','<i4')])

In [13]:
x['a']

array([1., 3.])

In [14]:
type(x[0][0])

numpy.float64

In [15]:
type(x['a'][0])

numpy.float64

In [16]:
#Creating an array from sub-classes:

In [17]:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [18]:
#Convert the input to an array.

In [19]:
#Convert a list into an array:

In [20]:
 a = [1, 2]
np.array(a)

array([1, 2])

In [21]:
np.asarray(a)

array([1, 2])

In [22]:
a = np.array([1, 2]) #Existing arrays are not copied
a

array([1, 2])

In [23]:
b = np.array([1, 2])


In [24]:
id(a)

1435144604608

In [25]:
np.asarray([1, 2]) is np.array([1, 2])

False

In [26]:
#If dtype is set, array is copied only if dtype does not match:

In [27]:
a = np.array([1, 2], dtype=np.float32)
b = np.asarray([1, 2], dtype=np.float32)

In [28]:
a is b

False

In [29]:
np.asarray([1, 2], dtype=np.float32) is np.array([1, 2], dtype=np.float32)

False

In [30]:
np.asarray(a, dtype=np.float64) is a

False

In [31]:
# ndarray subclasses are not passed through

In [32]:
issubclass(np.matrix, np.ndarray)

True

In [33]:
a = np.array([1, 2])
a

array([1, 2])

In [34]:
np.asarray(a) is a

True

In [35]:
np.asanyarray(a) is a

True

# numpy.asanyarray

In [36]:
a = [1, 2]
np.asanyarray(a)
np.array(a)

array([1, 2])

In [37]:
a = np.matrix([1, 2])
np.asanyarray(a)

matrix([[1, 2]])

In [38]:
np.asanyarray(a) is a

True

In [39]:
id(a)

1435144648184

In [40]:
b  = np.array(a,copy=False)  

In [41]:
#Create an array x, with a reference y and a copy z:

In [42]:
id(b)

1435144773184

In [43]:
x = np.array([1, 2, 3])
id(x)

1435144771504

In [44]:
y = x

In [45]:
id(y) 

1435144771504

In [46]:
x

array([1, 2, 3])

In [47]:
x[0] = 7878

In [48]:
y

array([7878,    2,    3])

In [49]:
z = np.copy(x)

In [50]:
z[1] =87868

In [51]:
z

array([ 7878, 87868,     3])

In [52]:
x

array([7878,    2,    3])

In [53]:
x[0] == y[0]

True

In [54]:
x[0] == z[0]

True

# numpy.fromfunction

In [55]:
#Construct an array by executing a function over each coordinate.

In [56]:
def test(i , j ):
    if i ==j :
        return True 
    else :
        return False 

In [57]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [58]:
np.fromfunction(lambda i, j: i / j, (3, 3), dtype=int)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [59]:
#Create a new 1-dimensional array from an iterable object.

In [60]:
iterable = (x*x for x in range(5))
print(iterable)

<generator object <genexpr> at 0x0000014E2548D228>


In [61]:
iterable

<generator object <genexpr> at 0x0000014E2548D228>

In [62]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [63]:
#A new 1-D array initialized from text data in a string

In [64]:
np.fromstring('1 4 ', sep=' ')

array([1., 4.])

In [65]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [66]:
x1=np.array([1,2,3,4])

In [67]:
x2=np.array(['a','dd','xyz','12'])

In [68]:
x3=np.array([1.1,2,3,4])

In [69]:
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')

In [70]:
r 

rec.array([(1, 'a', 1.1), (2, 'dd', 2. ), (3, 'xyz', 3. ), (4, '12', 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8')])

In [71]:
type(r[1][1])

numpy.str_

In [72]:
r.a

array([1, 2, 3, 4])

# data types

In [73]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [74]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape) #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype) #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix:  (3, 3)
Data type of this matrix:  int32


In [75]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [76]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [285]:
import numpy as np 

print("A series of numbers:",np.arange(10.8,20.8,.8)) # A series of numbers from low to high

A series of numbers: [10.8 11.6 12.4 13.2 14.  14.8 15.6 16.4 17.2 18.  18.8 19.6 20.4]


In [292]:
range(2,10,2)

range(2, 10, 2)

In [295]:
a = np.arange(2,10.5,.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [296]:
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [80]:
for i in np.arange(10.8,20.8,.8):
    print(i)

10.8
11.600000000000001
12.400000000000002
13.200000000000003
14.000000000000004
14.800000000000004
15.600000000000005
16.400000000000006
17.200000000000006
18.000000000000007
18.800000000000008
19.60000000000001
20.40000000000001


In [82]:
print("Numbers spaced apart by 2:",np.arange(0,11,2)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [83]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [84]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [298]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,10))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


# Matrix creation

In [299]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [87]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [300]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [89]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [90]:
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [335]:
print("Empty matrix\n-------------\n", np.empty((3,5,2)))

Empty matrix
-------------
 [[[7.09047313e-312 9.58487353e-322]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 5.02034658e+175]
  [4.66541136e-033 1.45233291e-051]
  [1.80063196e+185 4.03551729e+175]]

 [[5.01163106e+217 5.49419094e-143]
  [9.80058441e+252 1.30304358e-142]
  [2.14027814e+161 5.04621383e+180]
  [4.50618615e-144 7.79952704e-143]
  [1.80135035e+185 9.58876254e-043]]

 [[9.76118937e+165 5.16297946e-066]
  [1.41529403e+161 6.00736899e-067]
  [5.16656595e+097 1.90302825e-052]
  [4.26263407e+126 9.30350598e+199]
  [3.67152475e-062 1.58268989e-319]]]


In [92]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [93]:
np.arange(3)

array([0, 1, 2])

In [94]:
np.arange(3.0)

array([0., 1., 2.])

In [96]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [97]:
np.arange(3,7,2)

array([3, 5])

In [307]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [305]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [308]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [101]:
#Return numbers spaced evenly on a log scale.

In [330]:
np.logspace(2.0, 3.0, num=5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [119]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [309]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [105]:
#Extract a diagonal or construct a diagonal array.

In [334]:
np.arange(9).reshape((3,1,3,1))

array([[[[0],
         [1],
         [2]]],


       [[[3],
         [4],
         [5]]],


       [[[6],
         [7],
         [8]]]])

In [310]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [358]:
x = np.arange(25).reshape(((5,5)))

In [341]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [344]:
np.diag(x , k = -2)

array([10, 16, 22])

In [151]:
np.diag(x, k=-2)

array([6])

In [346]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [356]:
np.diag(x , k = -2)

array([10, 16, 22])

In [347]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]])

In [112]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [113]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [348]:
np.diagflat([1,2,3], 2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [115]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [352]:
np.tri(5, 5, -1, dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [178]:
np.tri(7,9 ,-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0.]])

In [174]:
#return a Lower triangle of an array.

In [357]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [354]:
#return Upper triangle of an array.

In [355]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# Random number generation

In [360]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(10,5)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.98422102 0.86610166 0.55973058 0.06503386 0.81554445]
 [0.49928761 0.06011417 0.07484675 0.63392252 0.12039662]
 [0.8552994  0.71040859 0.98482383 0.85809243 0.96880325]
 [0.32112677 0.93257078 0.36734206 0.71074846 0.49046477]
 [0.76561179 0.66804931 0.46016651 0.18920051 0.37990296]
 [0.27668401 0.65807612 0.25024313 0.6761369  0.0027022 ]
 [0.06911295 0.82589268 0.98085953 0.66363107 0.48628179]
 [0.70338307 0.19114635 0.76911446 0.74868748 0.23182812]
 [0.43738544 0.20989212 0.12026943 0.81887143 0.9681424 ]
 [0.80990832 0.0339641  0.31259079 0.85701473 0.05266248]]


In [186]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-1.9023134   0.26327142 -0.00930874]
 [-0.30028501 -0.71968493 -0.85876669]
 [ 0.49541573  0.11027938 -0.15485397]
 [ 1.88424506 -1.2370396  -0.50926019]]


In [190]:
print("Random integer vector:",np.random.randint(1,10,100)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random integer vector: [6 5 7 2 9 5 6 2 3 7 9 8 5 4 6 8 6 6 4 6 1 7 8 6 8 7 5 5 3 1 1 6 9 5 9 2 5
 8 6 8 8 1 5 3 2 6 7 8 6 8 6 6 2 7 5 5 2 6 7 5 7 5 3 1 7 1 6 1 7 5 9 7 6 4
 6 7 6 8 8 4 4 5 2 5 2 7 4 2 6 2 2 8 3 3 9 2 8 6 5 4]

Random integer matrix
[[82 53 58 44]
 [98 84  9 24]
 [43 81 97 51]
 [44 10 46 83]]

20 samples drawn from a dice throw: [2 6 1 2 5 2 1 1 4 2 5 4 5 6 5 4 2 6 2 1]


# Reshaping

In [364]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)


In [365]:
a

array([54, 98, 55, 11, 64, 98, 89, 87, 70, 21,  4, 70, 33, 47, 37, 98, 51,
       67, 47, 64,  7, 84, 38, 65, 47,  1, 72, 64, 52, 40])

In [366]:
b

array([[[54, 98, 55, 11, 64],
        [98, 89, 87, 70, 21],
        [ 4, 70, 33, 47, 37]],

       [[98, 51, 67, 47, 64],
        [ 7, 84, 38, 65, 47],
        [ 1, 72, 64, 52, 40]]])

In [367]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)



Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [368]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [54 98 55 11 64 98 89 87 70 21  4 70 33 47 37 98 51 67 47 64  7 84 38 65
 47  1 72 64 52 40] 
 --------------------

b looks like
 -------------------- 
 [[[54 98 55 11 64]
  [98 89 87 70 21]
  [ 4 70 33 47 37]]

 [[98 51 67 47 64]
  [ 7 84 38 65 47]
  [ 1 72 64 52 40]]] 
 --------------------

c looks like
 -------------------- 
 [[54 98 55 11 64]
 [98 89 87 70 21]
 [ 4 70 33 47 37]
 [98 51 67 47 64]
 [ 7 84 38 65 47]
 [ 1 72 64 52 40]] 
 --------------------


In [369]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))



Vector of random integers
 -------------------------------------------------- 
 [58 52 22 35  6 65 73 63 19 19]

Here is the sorted vector
 -------------------------------------------------- 
 [ 6 19 19 22 35 52 58 63 65 73]


In [370]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[40 78 33 11 59]
 [23 78 83 67 31]
 [25 17 65 43 55]
 [51 48 16 37  4]
 [77 65 98  6 74]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[11 33 40 59 78]
 [23 31 67 78 83]
 [17 25 43 55 65]
 [ 4 16 37 48 51]
 [ 6 65 74 77 98]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[23 17 16  6  4]
 [25 48 33 11 31]
 [40 65 65 37 55]
 [51 78 83 43 59]
 [77 78 98 67 74]]


In [371]:
M

array([[40, 78, 33, 11, 59],
       [23, 78, 83, 67, 31],
       [25, 17, 65, 43, 55],
       [51, 48, 16, 37,  4],
       [77, 65, 98,  6, 74]])

In [372]:
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[23 17 16  6  4]
 [25 48 33 11 31]
 [40 65 65 37 55]
 [51 78 83 43 59]
 [77 78 98 67 74]]


In [373]:
a

array([54, 98, 55, 11, 64, 98, 89, 87, 70, 21,  4, 70, 33, 47, 37, 98, 51,
       67, 47, 64,  7, 84, 38, 65, 47,  1, 72, 64, 52, 40])

In [374]:
b

array([[[54, 98, 55, 11, 64],
        [98, 89, 87, 70, 21],
        [ 4, 70, 33, 47, 37]],

       [[98, 51, 67, 47, 64],
        [ 7, 84, 38, 65, 47],
        [ 1, 72, 64, 52, 40]]])

In [375]:
print("Max of a:", a.max())
print("Max of b:", b.max())
b

Max of a: 98
Max of b: 98


array([[[54, 98, 55, 11, 64],
        [98, 89, 87, 70, 21],
        [ 4, 70, 33, 47, 37]],

       [[98, 51, 67, 47, 64],
        [ 7, 84, 38, 65, 47],
        [ 1, 72, 64, 52, 40]]])

In [378]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(6,5)
b

array([[35, 94, 70, 45, 57],
       [89,  8, 90, 25, 31],
       [90, 71,  2, 54, 79],
       [ 6, 24,  6, 32, 23],
       [33, 90, 32, 26, 35],
       [34, 79, 38, 41, 22]])

In [379]:

print("Max of c location:", b.argmax(axis = 0 ))

Max of c location: [2 0 1 2 2]


# Indexing and slicing

In [380]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [381]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [225]:
print("Elements from 3rd to 5th index are:", arr[3:6])


Elements from 3rd to 5th index are: [3 4 5]


In [226]:
print("Elements up to 4th index are:", arr[:4])


Elements up to 4th index are: [0 1 2 3]


In [227]:
print("Elements from last backwards are:", arr[-1::-1])


Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]


In [228]:
print("3 Elements from last backwards are:", arr[-1:-6:-2])


3 Elements from last backwards are: [10  8  6]


In [229]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [230]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [382]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

Matrix of random 2-digit numbers
--------------------------------
 [[90 76 57 41 85]
 [98 77 66 70 71]
 [21 86 36 35 86]]


In [383]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[0][2])



Double bracket indexing
------------------------
Element in row index 1 and column index 2: 57


In [236]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 32

Row or column extract
----------------------


In [237]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [85 26 73 23 31]
Entire column at index 3: [30 49 23]


In [238]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[49 59]
 [23 31]]


In [239]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[47 30]
 [37 49]]


# Subseting

In [384]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


Matrix of random 2-digit numbers
--------------------------------
 [[62 12 57 64 88]
 [86 94 52 14 34]
 [57 52 33 80 74]]


In [386]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [62 57 64 88 86 94 52 57 52 80 74]


In [385]:
mat>50

array([[ True, False,  True,  True,  True],
       [ True,  True,  True, False, False],
       [ True,  True, False,  True,  True]])

# Slicing

In [387]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [388]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [389]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [390]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [391]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [392]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [262]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [263]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [264]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[9 9 9]
 [7 8 9]
 [6 5 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[9 8 8]
 [6 1 9]
 [4 4 2]]


In [170]:
print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)



Addition
------------------
 [[13 14 11]
 [ 3 11 16]
 [ 9 13  8]]

Multiplication
------------------
 [[42 45 18]
 [ 2 18 63]
 [ 8 42 15]]


In [265]:
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[1.         1.125      1.125     ]
 [1.16666667 8.         1.        ]
 [1.5        1.25       4.        ]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[ 9 11 11]
 [ 9 22  9]
 [10  7 20]]


In [266]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[109 109 109]
 [107 108 109]
 [106 105 108]]


In [267]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


Exponentiation, matrix cubed here
----------------------------------------
 [[729 729 729]
 [343 512 729]
 [216 125 512]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[3.         3.         3.        ]
 [2.64575131 2.82842712 3.        ]
 [2.44948974 2.23606798 2.82842712]]


# Broadcasting

In [268]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [282]:
start = np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [283]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [284]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [272]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [273]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [180]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+add_scalar)

[[ 100.  100.  100.]
 [ 100.  100.  100.]
 [ 100.  100.  100.]
 [ 100.  100.  100.]]


# Array Math

In [274]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[6 1 1]
 [7 6 4]
 [6 2 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[9 2 6]
 [2 8 6]
 [3 6 1]]


In [275]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.44948974 1.         1.        ]
 [2.64575131 2.44948974 2.        ]
 [2.44948974 1.41421356 2.        ]]


In [276]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[ 403.42879349    2.71828183    2.71828183]
 [1096.63315843  403.42879349   54.59815003]
 [ 403.42879349    7.3890561    54.59815003]]


In [277]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))



10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.77815125 0.         0.        ]
 [0.84509804 0.77815125 0.60205999]
 [0.77815125 0.30103    0.60205999]]
